## Практическое задание №1. Основные понятия и структуры PyTorch

In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3, 4, 5)
a.type()

'torch.FloatTensor'

In [3]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
b = a.reshape(6, 10)
b

tensor([[0.3675, 0.5951, 0.5284, 0.4573, 0.6092, 0.3529, 0.3440, 0.3560, 0.5980,
         0.1894],
        [0.3338, 0.0119, 0.6926, 0.0058, 0.3233, 0.7885, 0.4038, 0.7669, 0.9064,
         0.5149],
        [0.2574, 0.8493, 0.3391, 0.0375, 0.5000, 0.9521, 0.1437, 0.1800, 0.7296,
         0.4103],
        [0.7607, 0.3587, 0.7192, 0.8980, 0.3806, 0.7711, 0.7162, 0.9978, 0.4646,
         0.3410],
        [0.1591, 0.0172, 0.0833, 0.5753, 0.4219, 0.2541, 0.0420, 0.3197, 0.5350,
         0.5834],
        [0.3058, 0.1884, 0.1190, 0.8156, 0.0662, 0.5643, 0.9078, 0.9883, 0.0019,
         0.8628]])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
a * torch.tensor([1, 4, 2, 2, 1])

tensor([[[0.3675, 2.3804, 1.0568, 0.9147, 0.6092],
         [0.3529, 1.3761, 0.7120, 1.1960, 0.1894],
         [0.3338, 0.0475, 1.3853, 0.0116, 0.3233],
         [0.7885, 1.6152, 1.5339, 1.8128, 0.5149]],

        [[0.2574, 3.3972, 0.6781, 0.0751, 0.5000],
         [0.9521, 0.5747, 0.3600, 1.4591, 0.4103],
         [0.7607, 1.4349, 1.4383, 1.7961, 0.3806],
         [0.7711, 2.8648, 1.9956, 0.9292, 0.3410]],

        [[0.1591, 0.0687, 0.1666, 1.1505, 0.4219],
         [0.2541, 0.1679, 0.6394, 1.0700, 0.5834],
         [0.3058, 0.7536, 0.2380, 1.6313, 0.0662],
         [0.5643, 3.6310, 1.9766, 0.0038, 0.8628]]])

In [6]:
b.shape

torch.Size([6, 10])

In [7]:
b[:, :6]

tensor([[0.3675, 0.5951, 0.5284, 0.4573, 0.6092, 0.3529],
        [0.3338, 0.0119, 0.6926, 0.0058, 0.3233, 0.7885],
        [0.2574, 0.8493, 0.3391, 0.0375, 0.5000, 0.9521],
        [0.7607, 0.3587, 0.7192, 0.8980, 0.3806, 0.7711],
        [0.1591, 0.0172, 0.0833, 0.5753, 0.4219, 0.2541],
        [0.3058, 0.1884, 0.1190, 0.8156, 0.0662, 0.5643]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
d = b[:, :6] * (b[:, :6])
print(d)
print(d.shape)

tensor([[1.3503e-01, 3.5414e-01, 2.7921e-01, 2.0915e-01, 3.7109e-01, 1.2452e-01],
        [1.1144e-01, 1.4087e-04, 4.7974e-01, 3.3782e-05, 1.0450e-01, 6.2177e-01],
        [6.6274e-02, 7.2131e-01, 1.1496e-01, 1.4093e-03, 2.4999e-01, 9.0655e-01],
        [5.7863e-01, 1.2868e-01, 5.1718e-01, 8.0647e-01, 1.4484e-01, 5.9463e-01],
        [2.5322e-02, 2.9480e-04, 6.9424e-03, 3.3092e-01, 1.7801e-01, 6.4582e-02],
        [9.3528e-02, 3.5495e-02, 1.4166e-02, 6.6525e-01, 4.3830e-03, 3.1845e-01]])
torch.Size([6, 6])


In [9]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
v = torch.tensor([1, 0.5, 2], requires_grad=True)
v.grad

In [10]:
z = v ** 3 + v - 75 * v
z

tensor([ -73.0000,  -36.8750, -140.0000], grad_fn=<SubBackward0>)

In [11]:
z.backward(v)

In [12]:
v.grad

tensor([ -71.0000,  -36.6250, -124.0000])

In [13]:
# Создайте единичный тензор размера 5x6
o=torch.ones(5,6)
o

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [14]:
# Переведите его в формат numpy
import numpy as np
o.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)